import React from 'react';
import { Link } from 'react-router-dom';
import { Paper, Button } from 'components/common';
import { getIcon } from 'helpers';
import { BindingAction, IDivision } from 'common/models';
import { ButtonColors, ButtonVariant, Routes, Icons } from 'common/enums';
import styles from '../styles.module.scss';

const ICON_STYLES = {
  marginRight: '5px',
};

interface Props {
  divisions: IDivision[];
  onCsvLoaderBtn: BindingAction;
  onAddDivision: BindingAction;
  toggleLibraryPopup: BindingAction;
  onAutogeneratePools: BindingAction;
  onAutogenerateDivisions: BindingAction;
}

const Navigation = ({
  divisions,
  onCsvLoaderBtn,
  onAddDivision,
  toggleLibraryPopup,
  onAutogeneratePools,
  onAutogenerateDivisions,
}: Props) => (
  <Paper sticky={true}>
    <div className={styles.mainMenu}>
      <div className={styles.btnsWraper}>
        <p className={styles.loadBtsWrapper}>
          <Link className={styles.libraryBtn} to={Routes.LIBRARY_MANAGER}>
            {getIcon(Icons.GET_APP, ICON_STYLES)} Load From Library
          </Link>
          <Button
            onClick={toggleLibraryPopup}
            icon={getIcon(Icons.PUBLISH, ICON_STYLES)}
            variant={ButtonVariant.TEXT}
            color={ButtonColors.SECONDARY}
            label="Save to Library"
          />
          <Button
            color={ButtonColors.SECONDARY}
            variant={ButtonVariant.TEXT}
            onClick={onCsvLoaderBtn}
            label="Import from CSV"
          />
        </p>
        <div className={styles.btnWrapper}>
          <div>
            <Button
              variant={ButtonVariant.CONTAINED}
              color={ButtonColors.PRIMARY}
              onClick={onAddDivision}
              label="+ Add Division"
            />
          </div>
          <div>
            <Button
              color={ButtonColors.PRIMARY}
              label="Auto-generate Divisions"
              variant={ButtonVariant.CONTAINED}
              disabled={divisions.length > 0}
              onClick={onAutogenerateDivisions}
            />  
          </div>
          <div>
            <Button
              variant={ButtonVariant.CONTAINED}
              color={ButtonColors.PRIMARY}
              onClick={onAutogeneratePools}
              disabled={divisions.length < 1}
              label="Auto-generate Pools"
            />
          </div>
        </div>
      </div>
    </div>
  </Paper>
);

export default Navigation;
