export const LOAD_PROMO_CODES_START = 'LOAD_PROMO_CODES_START';
export const LOAD_PROMO_CODES_SUCCESS = 'LOAD_PROMO_CODES_SUCCESS';
export const LOAD_PROMO_CODES_FAILURE = 'LOAD_PROMO_CODES_FAILURE';
export const ADD_PROMO_CODE_SUCCESS = 'ADD_PROMO_CODE_SUCCESS';
export const ADD_PROMO_CODE_FAILURE = 'ADD_PROMO_CODE_FAILURE';

export const DELETE_PROMO_CODE_SUCCESS = 'DELETE_PROMO_CODE_SUCCESS';
export const DELETE_PROMO_CODE_FAILURE = 'DELETE_PROMO_CODE_FAILURE';
export const UPDATE_PROMO_CODE_SUCCESS = 'UPDATE_PROMO_CODE_SUCCESS';
export const UPDATE_PROMO_CODE_FAILURE = 'UPDATE_PROMO_CODE_FAILURE';

export type PromoCodesAction = { type: string; payload: any };
