export const DATA_FETCH_SUCCESS = 'EVENT_LINK:DATA_FETCH_SUCCESS';
export const RESPONSES_FETCH_SUCCESS = 'EVENT_LINK:RESPONSES_FETCH_SUCCESS';
export const OPTIONS_FETCH_SUCCESS = 'EVENT_LINK:OPTIONS_FETCH_SUCCESS';
export const MESSAGES_FETCH_SUCCESS = 'EVENT_LINK:MESSAGES_FETCH_SUCCESS';
export const SEND_SAVED_MESSAGES_SUCCESS =
  'EVENT_LINK:SEND_SAVED_MESSAGES_SUCCESS';
export const DELETE_MESSAGES_SUCCESS = 'EVENT_LINK:DELETE_MESSAGES_SUCCESS';
export const REFRESH_RESPONSE_SUCCESS = 'EVENT_LINK:REFRESH_RESPONSE_SUCCESS';
export const MESSAGE_FETCH_SUCCESS = 'EVENT_LINK:MESSAGE_FETCH_SUCCESS';
