export const EVENTS_FETCH_SUCCESS = 'COMPLEXITIES_EVENTS_FETCH_SUCCESS';
export const FACILITIES_FETCH_SUCCESS = 'COMPLEXITIES_FACILITIES_FETCH_SUCCESS';
export const FIELDS_FETCH_SUCCESS = 'COMPLEXITIES_FIELDS_FETCH_SUCCESS';
export const BACKUP_PLANS_FETCH_SUCCESS =
  'COMPLEXITIES_BACKUP_PLANS_FETCH_SUCCESS';
export const ADD_BACKUP_PLAN_SUCCESS = 'COMPLEXITIES_ADD_BACKUP_PLAN_SUCCESS';
export const DELETE_BACKUP_PLAN = 'COMPLEXITIES_DELETE_BACKUP_PLAN';
export const UPDATE_BACKUP_PLAN = 'COMPLEXITIES_UPDATE_BACKUP_PLAN';

export const LOAD_TIMESLOTS_START = 'LOAD_TIMESLOTS_START';
export const LOAD_TIMESLOTS_SUCCESS = 'LOAD_TIMESLOTS_SUCCESS';
export const LOAD_TIMESLOTS_FAILURE = 'LOAD_TIMESLOTS_FAILURE';

export const TOGGLE_BACK_UP_STATUS_SECCESS = 'TOGGLE_BACK_UP_STATUS_SECCESS';
export const TOGGLE_BACK_UP_STATUS_FAILURE = 'TOGGLE_BACK_UP_STATUS_FAILURE';
