export const EVENTS_FETCH_SUCCESS = "EVENTS_FETCH_SUCCESS";
export const EVENTS_FETCH_FAILURE = "EVENTS_FETCH_FAILURE";
export const DASHBOARD_FETCH_START = "DASHBOARD_FETCH_START";
export const CALENDAR_EVENTS_FETCH_START =
  "DASHBOARD_CALENDAR_EVENTS_FETCH_START";
export const CALENDAR_EVENTS_FETCH_SUCCESS =
  "DASHBOARD_CALENDAR_EVENTS_FETCH_SUCCESS";
export const DASHBOARD_CLEAR =
  "DASHBOARD_CLEAR";
export const DASHBOARD_CARDS_FETCH_SUCCESS =
  "DASHBOARD_CARDS_FETCH_SUCCESS";
